name: Java CI with Gradle

on:
  push:
    branches: [ "ustinovami" ] 
  pull_request:
    branches: [ "ustinovami" ]
  schedule:
    - cron: '30 12 * * 3'  # в среду в 12:30
    - cron: '0 22 * * 5'   # в пятницу в 22:00

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest]
        version: [21]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - name: Make gradlew executable
        run: chmod +x gradlew
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.version }}
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 
      - name: Clean Gradle cache
        run: ./gradlew clean
      - name: Build with Gradle Wrapper
        run: ./gradlew build

  dependency-submission:
    strategy:
      matrix:
        os: [macos-latest]
        version: [21]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - name: Make gradlew executable
        run: chmod +x gradlew
      - name: Set up JDK
        uses: actions/setup-java@v4 
        with: 
          java-version: ${{ matrix.version }}
          distribution: 'temurin'
      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@af1da67850ed9a4cedd57bfd976089dd991e2582
